#!/bin/bash
#
# The 'run' performs a simple test that verifies that STI image.
IMAGE_NAME=quay.io/ausnimbus/s2i-observe

# Install docker-squash
pip install docker-squash

# Docker login
docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io

test_docker_build() {
	echo "Testing the 'docker build'..."
	docker build -t $IMAGE_NAME .
}

test_docker_run_usage() {
	echo "Testing 'docker run' usage..."
	docker run --rm ${IMAGE_NAME} &>/dev/null
}

check_result() {
	local result="$1"
	if [[ "$result" != "0" ]]; then
		echo "STI image '${IMAGE_NAME}' test FAILED (exit code: ${result})"
		exit $result
	fi
}

test_docker_build
check_result $?

test_docker_run_usage
check_result $?

docker-squash -t ${IMAGE_NAME} ${IMAGE_NAME}
docker push ${IMAGE_NAME}
