#!/bin/bash
#
# The 'run' performs a simple test that verifies that STI image.
# The main focus is that the image prints out the base-usage properly.
IMAGE_NAME=${TRAVIS_REPO_SLUG-ausnimbus/s2i-observe}

test_docker_build() {
	echo "Testing the 'docker build'..."
	docker build -t $IMAGE_NAME .
}

test_docker_run_usage() {
	echo "Testing 'docker run' usage..."
	docker run --rm ${IMAGE_NAME} &>/dev/null
}

check_result() {
	local result="$1"
	if [[ "$result" != "0" ]]; then
		echo "STI image '${IMAGE_NAME}' test FAILED (exit code: ${result})"
		exit $result
	fi
}

test_docker_build
check_result $?

test_docker_run_usage
check_result $?

curl -X POST -H "Content-Type: application/json" --data '{"docker_tag": latest}' https://registry.hub.docker.com/u/$TRAVIS_REPO_SLUG/trigger/$DOCKER_HUB_TOKEN/

